Pages
ishimwezachee/Microverse_Capstone3 pull request #1
Opened 2022-01-13 15:10 UTC by ishimwezachee

- An API for the project Covid
- Followed design guidelines
- Interactions:
- Home page: When the page loads, the web app shows the Country's name, TOTAL-CONFIRMED TODAY RECOVERED and ------ When the user clicks (or taps) on a MORE INFO the application navigates to the details page.
- Details page: the web app retrieves data from the API to show detailed data in the MORE INFO and When the user clicks on --- the "Back" button (<), the user navigates to the home page.
- Created unit and integration tests.
- The project is a single-page application (SPA) built with React and Redux.
- Every page (the main page and the pages for each item) have a unique route within the SPA.
- The project is deployed and accessible online Live Link and also (added a link to the online version of the app to README file).
- Recorded a video for documentation Loom Record

2022-01-13 17:19 UTC, mikenath223 requested changes
Hello @ishimwezachee 

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._


Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-13 17:19 UTC, mikenath223 commented on README.md
> +[Video Demo](https://www.loom.com/share/c1bafc0ccb0d4ed4995be48480abd796)
- [ ] In the video you are expected to talk about a piece of code that you found interesting. Please record an additional video highlighting this.

2022-01-13 17:20 UTC, mikenath223 commented on src/App.test.js
> +    expect(app).toMatchSnapshot();
- [ ] Some snapshot tests are failing kindly update them.

2022-01-14 08:59 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hi there 👋🏽 , 

Great work on making the changes requested by a previous reviewer 👏 
To highlight 👍🏽 
- All tests pass now
- You showed an interesting part of your code.
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] I suggest that you consider adding instructions on how to clone and run your project to your README file. This would ensure that anyone, no matter their programming background would be able to run your project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 09:42 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @ishimwezachee , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

Cheers and Happy coding!👏👏👏

2022-01-14 09:59 UTC, merged